services:
  api:
    container_name: api
    image: az204.api
    build:
      context: .
      dockerfile: Az204.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  azure-functions:
    image: az204.functions
    build:
      context: .
      dockerfile: Az204.Functions/Dockerfile
    ports:
      - "7071:8080"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - api

  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
        
volumes:
  redis-data: