services:
  api:
    container_name: api
    image: az204.api
    build:
      context: .
      dockerfile: Az204.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  azure-functions:
    container_name: azure-functions
    image: az204.functions
    build:
      context: .
      dockerfile: Az204.Functions/Dockerfile
    ports:
      - "7071:8080"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - api

  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
  
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    command: >
      azurite 
      --blobHost 0.0.0.0 
      --queueHost 0.0.0.0 
      --tableHost 0.0.0.0 
      --blobPort 10000 
      --queuePort 10001 
      --tablePort 10002
      --skipApiVersionCheck
    depends_on:
      - api
        
volumes:
  redis-data:
  azurite-data: 